### ISSUE TITLE
Mesh2HRTF export from Blender error

### ISSUE THREAD

**Issue by terrainer** [Any2HRTF/Mesh2HRTF#52]
Trying to run the script to export my new mesh from Blender, now I'm getting this:

Python: Traceback (most recent call last):
  File "E:\Mesh2HRTF\3d_Model_uniform (2).blend\Text", line 50, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Terra\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\exportMesh2HRTF.py", line 179, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Terra\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\exportMesh2HRTF.py", line 302, in save
    with open(os.path.join(programPath, "..", "VERSION")) as read_version:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Mesh2HRTF\\Mesh2HRTF\\..\\VERSION'
Location: C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py:115

**Comment by terrainer** [comment]
Also want to not that the VERSION file is present in E:\Mesh2HRTF\Mesh2HRTF

**Comment by f-brinkmann** [comment]
What is you program path? It should be the folder containing the subfolders Mesh2Input, Numcalc, and Output2HRTF

**Comment by terrainer** [comment]
yep, screwed it up. I feel stupid now.
