### ISSUE TITLE
After post-processing there are no SOFA files generated

### ISSUE THREAD

**Issue by terrainer** [Any2HRTF/Mesh2HRTF#81]
After running my multi radius simulation, I am getting:

```
(mesh2hrtf) C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation>python finalize_hrtf_simulation.py
finalize_hrtf_simulation.py v3.01 started with SavePath = "C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation"

  ERROR: After post-processing there are no SOFA files generated in:
   "C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation\KEMAR_L"
```

Running Output2HRTF.py returns:

```
(mesh2hrtf) C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation\KEMAR_L>python Output2HRTF.py
  File "C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation\KEMAR_L\Output2HRTF.py", line 7
    Mesh2HRTF_version = '1.0.0
                        ^
SyntaxError: unterminated string literal (detected at line 7)
```

This is due to the closing apostrophe being on the next line, fixing this and running the command again returns:

```
(mesh2hrtf) C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation\KEMAR_L>python Output2HRTF.py
Traceback (most recent call last):
  File "C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation\KEMAR_L\Output2HRTF.py", line 34, in <module>
    m2h.output_to_hrtf(Mesh2HRTF_version, sourceType,
AttributeError: module 'mesh2hrtf' has no attribute 'output_to_hrtf'. Did you mean: 'output2hrtf'?
```

The mesh2hrtf python package is installed through anaconda, and I am running the script with the env active.
I tried changing output_to_hrtf in the Output2HRTF.py to output2hrtf as well, which returned:

```
(mesh2hrtf) C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation\KEMAR_L>python Output2HRTF.py
Traceback (most recent call last):
  File "C:\Mesh2HRTF\mesh2hrtf-tools\Finalize_HRTF_simulation\KEMAR_L\Output2HRTF.py", line 34, in <module>
    m2h.output2hrtf(Mesh2HRTF_version, sourceType,
TypeError: output2hrtf() takes from 0 to 1 positional arguments but 9 were given

```
My thoughts are that it could also possibly have to do with this from the NC{step}-{step}_log.txt:

```
Warning: There are some frequencies higher than the highest allowable frequency!
Number of frequencies outside the range= 50
The highest allowable frequency = 16609.6
```

I do not see anything out of the ordinary in the other logs. Also not sure why the highest allowable frequency is 16609.6.

**Comment by f-brinkmann** [comment]
Sorry to be the bad guy here but `finalize_hrtf_simulation.py` is not part of Mesh2HRTF. Can you first post that issue in the original repository please.
