### ISSUE TITLE
I am getting this error while exporting the Mesh from Bleneder.

### ISSUE THREAD

**Issue by abidshahriar** [Any2HRTF/Mesh2HRTF#89]
Traceback (most recent call last):
  File "<blender_console>", line 24, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.mesh2input.inp" error, could not be found

**Comment by germknoedlspeck** [comment]
Hi @abidshahriar,

which Blender and Mesh2HRTF version are you using?

**Comment by abidshahriar** [comment]
HI, @germknoedlspeck 

I had to use the blender 3.5. I tried installed the 2.79 version but i am struggling with the interface. 
Probably i have used the Mesh2HRTF what it is called the 0.99 version. Is that causing export issue? 


Mesh2HRTF that i am using : https://github.com/SDX-LV/Mesh2HRTF_contributions/releases/tag/v0.99

**Comment by germknoedlspeck** [comment]
Since the 0.99 version is not an official Mesh2HRTF release, I think @SDX-LV is the best person to answer this issue :)

**Comment by abidshahriar** [comment]
@germknoedlspeck i think i am gonna try the v1 as you mentioned to use with the newer version of Blender and lets see what happens.
