### ISSUE TITLE
Issue running pip

### ISSUE THREAD

**Issue by terrainer** [Any2HRTF/Mesh2HRTF#94]
Trying to reinstall Mesh2HRTF after a reformat, running into this problem:

` 
(mesh2hrtfvenv) E:\Mesh2HRTF-1.0.0>pip install -e .
Obtaining file:///E:/Mesh2HRTF-1.0.0
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "E:\Mesh2HRTF-1.0.0\mesh2hrtfvenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\Mesh2HRTF-1.0.0\mesh2hrtfvenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "E:\Mesh2HRTF-1.0.0\mesh2hrtfvenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Terra\AppData\Local\Temp\pip-build-env-80oaudbw\overlay\Lib\site-packages\setuptools\build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Terra\AppData\Local\Temp\pip-build-env-80oaudbw\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Terra\AppData\Local\Temp\pip-build-env-80oaudbw\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Terra\AppData\Local\Temp\pip-build-env-80oaudbw\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Terra\AppData\Local\Temp\pip-build-env-80oaudbw\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
        File "C:\Users\Terra\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2609: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip. 
`

It's probably something I'm doing wrong. I'm gonna have to start paying you guys for the tech support you're giving me on here 😂

**Comment by f-brinkmann** [comment]
No, I think this was our mistake. A non-unicode character sneaked into the readme file, which caused the error. Can you confirm that the error is fixed on the master branch? If yes, I'll make a patch release.

**Comment by terrainer** [comment]
> No, I think this was our mistake. A non-unicode character sneaked into the readme file, which caused the error. Can you confirm that the error is fixed on the master branch? If yes, I'll make a patch release.

Just replaced the readme file, can confirm that it's working now,
